# Regresión lineal en Python

## El paquete scikit-learn para regresión lineal y la selección de rasgos

In [1]:
#recursive feature

from sklearn.feature_selection import RFE
from sklearn.svm import SVR
import pandas as pd
import numpy as np


In [2]:
data = pd.read_csv("/Users/Luis Antonio Garza/Python proyectos/python-ml-course-master/datasets/ads/Advertising.csv")

In [3]:
feature_cols = ["TV", "Radio", "Newspaper"]

In [4]:
X = data[feature_cols]
Y = data["Sales"]

In [5]:
estimator = SVR(kernel="linear")
selector = RFE(estimator, 2, step=1)
selector = selector.fit(X,Y)

C:\DataSciencePython\lib\site-packages\sklearn\utils\validation.py:70: FutureWarning: Pass n_features_to_select=2 as keyword args. From version 1.0 (renaming of 0.25) passing these as positional arguments will result in an error
  warnings.warn(f"Pass {args_msg} as keyword args. From version "


In [6]:
selector.support_ #indica las variables seleccionadas para el modelo de feature_cols [tv, radio, newspaper]

array([ True,  True, False])

In [7]:
selector.ranking_

array([1, 1, 2])

In [8]:
from sklearn.linear_model import LinearRegression

In [10]:
X_pred = X[["TV", "Radio"]]

In [11]:
lm = LinearRegression()
lm.fit(X_pred, Y)

LinearRegression()

In [12]:
lm.intercept_

2.9210999124051362

In [13]:
lm.coef_

array([0.04575482, 0.18799423])

In [14]:
lm.score(X_pred, Y)

0.8971942610828956